# Generated by Django 2.0.6 on 2019-06-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time', models.DurationField()),
                ('pace', models.DurationField()),
                ('notes', models.TextField(blank=True)),
                ('race', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('date_purchased', models.DateField(blank=True, null=True)),
                ('starting_mileage', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5)),
            ],
        ),
    ]
