# Generated by Django 2.2.1 on 2019-07-14 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('runlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='owner',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', related_name='runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoe',
            name='owner',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', related_name='shoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
